<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(SolutionDir)\valheim.targets" />
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.18.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ServerSync\ServerSync.csproj" />
  </ItemGroup>
</Project>